const ProjectData = [
  {
    img: "https://res.cloudinary.com/da3avivzn/image/upload/v1692106569/My%20Portfolio/Rectangle_65-2_uwpsax.png",
    title: "",
    color: "#A800B7",
    name: "SBA",
    description: "Send And Recieve Money Anonymously",
    link: "https://sentbyanon.com/",
  },
  {
    img: "https://res.cloudinary.com/da3avivzn/image/upload/v1692106570/My%20Portfolio/Rectangle_65-1_hvbavg.png",
    title: "",
    color: "#EF8A17",
    name: "Spaces",
    description: "Web Designing Agency",
    link: "https://spaces-ui.xyz/",
  },
  {
    img: "https://res.cloudinary.com/da3avivzn/image/upload/v1692106568/My%20Portfolio/Rectangle_65_zygjwm.png",
    title: "",
    color: "#18B5BF",
    name: "Ticker",
    description: "Making reselling tickets possible",
    link: "https://ticker.africa/",
  },
  {
    img: "https://res.cloudinary.com/da3avivzn/image/upload/v1692106569/My%20Portfolio/Group_18_yuagdz.png",
    title: "",
    color: "#10263E",
    name: "SimplyBlogs",
    description: "A Blog",
    link: "https://cspaces1.netlify.app/",
  },
  {
    img: "https://res.cloudinary.com/da3avivzn/image/upload/v1686312229/SpacesBrandPage/Screen_Shot_2023-06-09_at_5.02.18_AM_roxha1.png",
    title: "",
    color: "#0197F6",
    name: "Portfolio",
    description: "Built For A Friend",
    link: "https://9celytics.netlify.app/",
  },
  {
    img: "https://res.cloudinary.com/da3avivzn/image/upload/v1692107080/My%20Portfolio/Group_20_okqizi.png",
    title: "",
    color: "#CB9833",
    name: "Credit Card",
    description: "My First App Built With React",
    link: "https://spaces-crediitcard.netlify.app/",
  },
];
export default ProjectData;
